# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            nimahajan
tagline:          'Personal Blog'
description:      'Sharing Ideas ..!'
url:              http://www.nimahajan.com
baseurl:          /

author:
  name:           'Nilesh Mahajan'
  url:            https://twitter.com/nilesh_mahajan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
